version: "3.9"
services:
  app:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/code
    links:
      - redis
      - postgres
  redis:
    image: redis:6.2.5-alpine
  postgres:
    image: postgres
volumes:
  logvolume: {}
